### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Chevalier2016** [Bara20/TroubleinTerroristTown#39]
L 07/25/2016 - 03:21:31: [SM] Exception reported: Invalid parameter number: 5
L 07/25/2016 - 03:21:31: [SM] Blaming: ttt_shop.smx()
L 07/25/2016 - 03:21:31: [SM] Call stack trace:
L 07/25/2016 - 03:21:31: [SM]   [0] GetNativeCell
L 07/25/2016 - 03:21:31: [SM]   [1] Line 301, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_shop.sp::Native_RegisterCustomItem()
L 07/25/2016 - 03:21:31: [SM]   [3] TTT_RegisterCustomItem
L 07/25/2016 - 03:21:31: [SM]   [4] Line 98, addons/sourcemod/scripting/ttt/ttt-weaponitems.sp::OnAllPluginsLoaded()

L 07/25/2016 - 03:22:29: [SM] Exception reported: Invalid entity (-1 - -1)
L 07/25/2016 - 03:22:29: [SM] Blaming: ttt_wallhack.smx()
L 07/25/2016 - 03:22:29: [SM] Call stack trace:
L 07/25/2016 - 03:22:29: [SM]   [0] GetEntityNetClass
L 07/25/2016 - 03:22:29: [SM]   [1] Line 481, C:\Users\Computer\Desktop\Sync\SourcePawn\scripting18\include\entity.inc::GetEntSendPropOffs()
L 07/25/2016 - 03:22:29: [SM]   [2] Line 279, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::UnhookGlow()
L 07/25/2016 - 03:22:29: [SM]   [3] Line 103, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::Event_PlayerReset()

L 07/25/2016 - 03:22:29: [SM] Exception reported: Invalid entity (-1 - -1)
L 07/25/2016 - 03:22:29: [SM] Blaming: ttt_glow.smx()
L 07/25/2016 - 03:22:29: [SM] Call stack trace:
L 07/25/2016 - 03:22:29: [SM]   [0] GetEntityNetClass
L 07/25/2016 - 03:22:29: [SM]   [1] Line 481, C:\Users\Computer\Desktop\Sync\SourcePawn\scripting18\include\entity.inc::GetEntSendPropOffs()
L 07/25/2016 - 03:22:29: [SM]   [2] Line 179, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_glow.sp::UnhookGlow()
L 07/25/2016 - 03:22:29: [SM]   [3] Line 50, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_glow.sp::Event_PlayerReset()

L 07/25/2016 - 03:22:29: [SM] Exception reported: Invalid entity (-1 - -1)
L 07/25/2016 - 03:22:29: [SM] Blaming: ttt_tagrenade.smx()
L 07/25/2016 - 03:22:29: [SM] Call stack trace:
L 07/25/2016 - 03:22:29: [SM]   [0] GetEntityNetClass
L 07/25/2016 - 03:22:29: [SM]   [1] Line 481, C:\Users\Computer\Desktop\Sync\SourcePawn\scripting18\include\entity.inc::GetEntSendPropOffs()
L 07/25/2016 - 03:22:29: [SM]   [2] Line 350, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_tagrenade.sp::UnhookGlow()
L 07/25/2016 - 03:22:29: [SM]   [3] Line 94, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_tagrenade.sp::Event_PlayerReset()

**Comment by good-live** [comment]
Which Version?

**Comment by Chevalier2016** [comment]
Most recent version of TTT. 
As for SM its sm 1.8 5919

**Comment by good-live** [comment]
Stable or dev?
Have you updated your include files?
The shop is working fine for me and the glow related errors shouldve been fixed with the last commits. (However there are still some)

**Comment by Chevalier2016** [comment]
Im using github latest commits which now latest commit was this https://github.com/Bara20/TroubleinTerroristTown/commit/87adbae445005d6fce39c7fb953c3ec4131999df
Also the include files wouldnt matter because i didnt compile the plugin, i used the smx provided in the zip.

and the errors stilll occur with latest for both event_PlayerReset & event_PlayerDeath

L 07/25/2016 - 16:12:15: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 07/25/2016 - 16:12:15: [SM] Blaming: ttt_wallhack.smx()
L 07/25/2016 - 16:12:15: [SM] Call stack trace:
L 07/25/2016 - 16:12:15: [SM]   [0] SetEntProp
L 07/25/2016 - 16:12:15: [SM]   [1] Line 286, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::UnhookGlow()
L 07/25/2016 - 16:12:15: [SM]   [2] Line 103, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::Event_PlayerReset()
L 07/25/2016 - 16:12:15: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 07/25/2016 - 16:12:15: [SM] Blaming: ttt_glow.smx()
L 07/25/2016 - 16:12:15: [SM] Call stack trace:
L 07/25/2016 - 16:12:15: [SM]   [0] SetEntProp
L 07/25/2016 - 16:12:15: [SM]   [1] Line 187, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_glow.sp::UnhookGlow()
L 07/25/2016 - 16:12:15: [SM]   [2] Line 50, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_glow.sp::Event_PlayerReset()
L 07/25/2016 - 16:12:15: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 07/25/2016 - 16:12:15: [SM] Blaming: ttt_tagrenade.smx()
L 07/25/2016 - 16:12:15: [SM] Call stack trace:
L 07/25/2016 - 16:12:15: [SM]   [0] SetEntProp
L 07/25/2016 - 16:12:15: [SM]   [1] Line 358, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_tagrenade.sp::UnhookGlow()
L 07/25/2016 - 16:12:15: [SM]   [2] Line 94, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_tagrenade.sp::Event_PlayerReset()

L 07/25/2016 - 16:08:35: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 9/player)
L 07/25/2016 - 16:08:35: [SM] Blaming: ttt_wallhack.smx()
L 07/25/2016 - 16:08:35: [SM] Call stack trace:
L 07/25/2016 - 16:08:35: [SM]   [0] SetEntProp
L 07/25/2016 - 16:08:35: [SM]   [1] Line 286, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::UnhookGlow()
L 07/25/2016 - 16:08:35: [SM]   [2] Line 114, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_wallhack.sp::Event_RoundReset()
L 07/25/2016 - 16:08:35: [SM]   [4] CS_TerminateRound
L 07/25/2016 - 16:08:35: [SM]   [5] Line 2659, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::CheckTeams()
L 07/25/2016 - 16:08:35: [SM]   [6] Line 1766, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::Event_PlayerDeath()

**Comment by good-live** [comment]
Yeah they still need to get fixed

**Comment by Chevalier2016** [comment]
Also what happened to the credits convars? they're missing and i cant compile my plugin since i_creditsII is missing.

**Comment by good-live** [comment]
The credits are part of the shop. Compiling works fine for me.

**Comment by Bara20** [comment]
"since i_creditsII is missing."
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_shop.sp#L45
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_shop.sp#L114
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_shop.sp#L477-L478

Yeah, creditsII is missing.

**Comment by Chevalier2016** [comment]
Well they were in ttt rather then ttt_shop, im aware of this now.

**Comment by Chevalier2016** [comment]
Heres some more

L 07/31/2016 - 16:29:34: [SM] Exception reported: Could not open file "/servers/giclanttt/csgo/addons/sourcemod/logs/ttt/ttt-16-07-31.log"
L 07/31/2016 - 16:29:34: [SM] Blaming: ttt.smx()
L 07/31/2016 - 16:29:34: [SM] Call stack trace:
L 07/31/2016 - 16:29:34: [SM]   [0] LogToFileEx
L 07/31/2016 - 16:29:34: [SM]   [1] Line 317, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::ShowLogs()
L 07/31/2016 - 16:29:34: [SM]   [2] Line 585, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::Event_RoundEndPre()
L 07/31/2016 - 16:29:34: [SM]   [4] CS_TerminateRound
L 07/31/2016 - 16:29:34: [SM]   [5] Line 2665, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::CheckTeams()
L 07/31/2016 - 16:29:34: [SM]   [6] Line 1766, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt.sp::Event_PlayerDeath()

L 07/31/2016 - 12:55:01: [SM] Exception reported: Invalid parameter number: 5
L 07/31/2016 - 12:55:01: [SM] Blaming: ttt_shop.smx()
L 07/31/2016 - 12:55:01: [SM] Call stack trace:
L 07/31/2016 - 12:55:01: [SM]   [0] GetNativeCell
L 07/31/2016 - 12:55:01: [SM]   [1] Line 301, C:\Users\Computer\Desktop\Sync\Projects\TTT\addons\sourcemod\scripting\ttt\ttt_shop.sp::Native_RegisterCustomItem()
L 07/31/2016 - 12:55:01: [SM]   [3] TTT_RegisterCustomItem
L 07/31/2016 - 12:55:01: [SM]   [4] Line 98, addons/sourcemod/scripting/ttt/ttt-weaponitems.sp::OnAllPluginsLoaded()

**Comment by Bara20** [comment]
Try latest (dev-)build from csgottt.com.

If it isn't fixed, let me know it here.

**Comment by Chevalier2016** [comment]
some new logs with latest

L 08/23/2016 - 20:53:28: [SM] Exception reported: Could not open file "/servers/giclanttt/csgo/addons/sourcemod/logs/ttt/ttt-16-08-23.log"
L 08/23/2016 - 20:53:28: [SM] Blaming: ttt.smx()
L 08/23/2016 - 20:53:28: [SM] Call stack trace:
L 08/23/2016 - 20:53:28: [SM]   [0] LogToFileEx
L 08/23/2016 - 20:53:28: [SM]   [1] Line 321, addons/sourcemod/scripting/ttt/ttt.sp::ShowLogs()
L 08/23/2016 - 20:53:28: [SM]   [2] Line 589, addons/sourcemod/scripting/ttt/ttt.sp::Event_RoundEndPre()
L 08/23/2016 - 20:53:28: [SM]   [4] CS_TerminateRound
L 08/23/2016 - 20:53:28: [SM]   [5] Line 2702, addons/sourcemod/scripting/ttt/ttt.sp::CheckTeams()
L 08/23/2016 - 20:53:28: [SM]   [6] Line 1796, addons/sourcemod/scripting/ttt/ttt.sp::Event_PlayerDeath()

L 08/23/2016 - 20:48:01: [SM] Exception reported: Invalid parameter number: 5
L 08/23/2016 - 20:48:01: [SM] Blaming: ttt_shop.smx()
L 08/23/2016 - 20:48:01: [SM] Call stack trace:
L 08/23/2016 - 20:48:01: [SM]   [0] GetNativeCell
L 08/23/2016 - 20:48:01: [SM]   [1] Line 301, addons/sourcemod/scripting/ttt/ttt_shop.sp::Native_RegisterCustomItem()
L 08/23/2016 - 20:48:01: [SM]   [3] TTT_RegisterCustomItem
L 08/23/2016 - 20:48:01: [SM]   [4] Line 74, addons/sourcemod/scripting/ttt/ttt-stations.sp::OnAllPluginsLoaded()

L 08/23/2016 - 20:48:01: [SM] Exception reported: Invalid parameter number: 5
L 08/23/2016 - 20:48:01: [SM] Blaming: ttt_shop.smx()
L 08/23/2016 - 20:48:01: [SM] Call stack trace:
L 08/23/2016 - 20:48:01: [SM]   [0] GetNativeCell
L 08/23/2016 - 20:48:01: [SM]   [1] Line 301, addons/sourcemod/scripting/ttt/ttt_shop.sp::Native_RegisterCustomItem()
L 08/23/2016 - 20:48:01: [SM]   [3] TTT_RegisterCustomItem
L 08/23/2016 - 20:48:01: [SM]   [4] Line 98, addons/sourcemod/scripting/ttt/ttt-weaponitems.sp::OnAllPluginsLoaded()

This next error is a major issue that on roundstart when the plugin selects a T/detective, the server stopps for 20 seconds as if its crashing then starts the game normally. 
L 08/23/2016 - 20:27:46: [SM] Exception reported: Script execution timed out
L 08/23/2016 - 20:27:46: [SM] Blaming: ttt_taser.smx()
L 08/23/2016 - 20:27:46: [SM] Call stack trace:
L 08/23/2016 - 20:27:46: [SM]   [1] Line 375, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::HasWeapon()
L 08/23/2016 - 20:27:46: [SM]   [2] Line 133, addons/sourcemod/scripting/ttt/ttt_taser.sp::TTT_OnClientGetRole()
L 08/23/2016 - 20:27:46: [SM]   [4] Call_Finish
L 08/23/2016 - 20:27:46: [SM]   [5] Line 952, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize()
L 08/23/2016 - 20:27:46: [SM]   [6] Line 849, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection()

**Comment by good-live** [comment]
Do you have any custom items, which havent got updates after the priority update of the shop?

**Comment by Chevalier2016** [comment]
i just saw i had older versions of talk override plugin + the ttt_talk_override but as for custom shop items no.

**Comment by Chevalier2016** [comment]
Oh actually i had ttt-weaponitems and ttt_weaponitems in my ftp, same for stations. Maybe that might of been it, ill test in a few hours if that was the issue.

**Comment by good-live** [comment]
I've created 2 issues for this. It would be nice if you could do that aswell in the future.
